"use client";

import React from "react";

// ═══════════════════════════════════════════════════
// HELPER COMPONENTS - White/light theme
// ═══════════════════════════════════════════════════
const navy = "#1b2a4a";
const teal = "#0d9488";
const red = "#ff4444";
const orange = "#f7931a";
const gold = "#d4af37";
const bg1 = "#ffffff";
const bg2 = "#faf5eb";
const bdr = "#e5e7eb";
const sub = "#64748b";
const muted = "#94a3b8";

function C({ center, children }: { center?: boolean; children: React.ReactNode }) {
  return <div style={{ width: "100%", minHeight: "280px", background: bg1, display: "flex", flexDirection: "column", position: "relative", overflow: "visible", ...(center ? { justifyContent: "center", alignItems: "center", padding: "40px" } : {}) }}>{children}</div>;
}
function T({ children }: { children: React.ReactNode }) {
  return <div style={{ padding: "28px 28px 0", fontSize: "10px", letterSpacing: "3px", color: muted, textTransform: "uppercase", fontFamily: "'Courier New',monospace" }}>{children}</div>;
}
function M({ gap, center, children }: { gap?: string; center?: boolean; children: React.ReactNode }) {
  return <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", padding: "20px 32px", gap: gap || "16px", ...(center ? { alignItems: "center" } : {}) }}>{children}</div>;
}
function P({ children }: { children: React.ReactNode }) {
  return <div style={{ padding: "0 28px 28px", textAlign: "center", color: navy, fontSize: "16px", fontFamily: "'Georgia',serif", fontStyle: "italic", lineHeight: 1.5 }}>{children}</div>;
}
function R2({ children }: { children: React.ReactNode }) {
  return <div style={{ flex: 1, display: "flex" }}>{children}</div>;
}
function H2({ br, children }: { br?: boolean; children: React.ReactNode }) {
  return <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "20px", ...(br ? { borderRight: `1px solid ${bdr}` } : {}) }}>{children}</div>;
}
function Sp() {
  return <div style={{ width: "60px", height: "1px", background: bdr, margin: "20px 0" }} />;
}
function Box({ accent, children }: { accent?: string; children: React.ReactNode }) {
  return <div style={{ textAlign: "center", padding: "16px", background: accent ? `${accent}0a` : bg2, borderRadius: "10px", border: `1px solid ${accent ? `${accent}33` : bdr}`, flex: 1, maxWidth: "140px" }}>{children}</div>;
}
function Bar({ pct, c }: { pct: string; c: string }) {
  return <div style={{ height: "20px", background: "#f0f0f0", borderRadius: "4px", overflow: "hidden" }}><div style={{ width: pct, height: "100%", background: c, borderRadius: "4px" }} /></div>;
}

// ═══════════════════════════════════════════════════
// MEME DATA - 36 total across 3 stages
// ═══════════════════════════════════════════════════

const memes = [
  // ───────────────────────────────────────
  // STAGE 1: FIAT IS FAILING (7)
  // ───────────────────────────────────────

  { stage:1, id:"fiat-graveyard", render:()=><C center><T>Dalio: every reserve currency dies</T><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"8px",width:"100%",maxWidth:"320px",marginTop:"16px"}}>{[["Roman Denarius","3rd c."],["Chinese Jiaozi","13th c."],["Dutch Guilder","1800"],["French Livre","1795"],["Spanish Real","1868"],["German Papiermark","1923"],["British Pound","1940s"],["Weimar mark","1923"],["US Dollar?","???"]].map(([c,yr],i)=><div key={c as string} style={{padding:"10px 6px",background:i===8?`${red}10`:bg2,border:i===8?`1px solid ${red}`:`1px solid ${bdr}`,borderRadius:"6px",textAlign:"center"}}><div style={{fontSize:i===8?22:18}}>{i===8?"⏳":"💀"}</div><div style={{fontSize:"9px",color:i===8?red:sub,marginTop:"4px",fontWeight:"bold"}}>{c}</div><div style={{fontSize:"8px",color:muted}}>{yr}</div></div>)}</div><P>The pattern is 100% consistent.<br/>No fiat currency has survived.</P></C> },

  { stage:1, id:"what-1-bought", render:()=><C><T>What $1 bought</T><M gap="16px">{[["1950","10 loaves of bread 🍞",gold],["1980","3 loaves 🍞","#aa8822"],["2000","1 loaf 🍞","#886611"],["2025","½ a loaf 🍞",muted]].map(([yr,item,c])=><div key={yr as string} style={{display:"flex",gap:"16px",alignItems:"baseline"}}><span style={{color:muted,fontSize:"11px",letterSpacing:"2px",minWidth:"40px"}}>{yr}</span><span style={{color:c as string,fontSize:"15px",fontFamily:"'Georgia',serif"}}>{item}</span></div>)}</M><P>Same dollar. Less bread. Every decade.</P></C> },

  { stage:1, id:"printer-go-brr", render:()=><C center><div style={{fontSize:"60px",marginBottom:"16px"}}>🖨️</div><div style={{display:"flex",flexDirection:"column",gap:"6px",maxWidth:"300px",width:"100%"}}>{[["2008","$700B bailout"],["2020","$4.5T stimulus"],["2023","$1.7T spending bill"],["2024","$35T+ national debt"]].map(([yr,amt])=><div key={yr as string} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:`1px solid ${bdr}`}}><span style={{color:sub,fontSize:"13px"}}>{yr}</span><span style={{color:red,fontSize:"13px",fontWeight:"bold"}}>{amt}</span></div>)}</div><P>They print. You pay.</P></C> },

  { stage:1, id:"king-vs-fed", render:()=><C><T>A brief history of the same trick</T><R2><H2 br><div style={{fontSize:"56px",marginBottom:"16px"}}>👑</div><div style={{fontSize:"14px",color:navy,fontWeight:"bold",marginBottom:"4px"}}>300 AD</div><div style={{fontSize:"13px",color:sub,textAlign:"center",lineHeight:1.6}}>Clip the coins.<br/>Mix in cheap metal.<br/>Hope nobody notices.</div></H2><H2><div style={{fontSize:"56px",marginBottom:"16px"}}>🏛️</div><div style={{fontSize:"14px",color:navy,fontWeight:"bold",marginBottom:"4px"}}>2025 AD</div><div style={{fontSize:"13px",color:sub,textAlign:"center",lineHeight:1.6}}>Print more dollars.<br/>Call it &ldquo;stimulus.&rdquo;<br/>Hope nobody notices.</div></H2></R2><P>Same trick. Better graphics.</P></C> },

  { stage:1, id:"mom-gdp", render:()=><C><T>A Mother&apos;s Day</T><div style={{flex:1,display:"flex",padding:"0 28px"}}><div style={{flex:1,display:"flex",flexDirection:"column",justifyContent:"center",gap:"3px"}}>{[["5:30 AM","Wake before everyone"],["6:00 AM","Pack lunches"],["7:00 AM","Dress kids, manage meltdowns"],["8:00 AM","School drop-off"],["9:00 AM","Clean, laundry, groceries"],["12:00 PM","Pay bills, schedule doctor"],["2:30 PM","Pick up, homework help"],["4:00 PM","Drive to practice"],["5:30 PM","Cook dinner"],["7:00 PM","Baths, stories, bedtime"],["9:00 PM","Prep for tomorrow"],["10:30 PM","Collapse"]].map(([t,d])=><div key={t} style={{display:"flex",gap:"12px",fontSize:"12px",lineHeight:1.6}}><span style={{color:muted,fontFamily:"'Courier New',monospace",fontSize:"10px",minWidth:"58px"}}>{t}</span><span style={{color:navy}}>{d}</span></div>)}</div><div style={{width:"120px",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",borderLeft:`1px solid ${bdr}`,paddingLeft:"20px"}}><div style={{fontSize:"10px",letterSpacing:"2px",color:muted,textTransform:"uppercase",marginBottom:"8px"}}>GDP<br/>Contribution</div><div style={{fontSize:"64px",fontWeight:"bold",color:"#ddd"}}>$0</div></div></div><P>If the ledger can&apos;t see her, the ledger is wrong.</P></C> },

  { stage:1, id:"grandma-vs-you", render:()=><C><T>Same savings. Different century.</T><M gap="32px"><div><div style={{fontSize:"11px",color:muted,letterSpacing:"2px",marginBottom:"8px"}}>1970</div><div style={{display:"flex",alignItems:"baseline",gap:"16px"}}><span style={{fontSize:"42px",color:gold,fontFamily:"'Georgia',serif",fontWeight:"bold"}}>$20,000</span><span style={{fontSize:"14px",color:muted}}>=</span><span style={{fontSize:"20px",color:gold}}>🏠</span><span style={{fontSize:"16px",color:sub,fontFamily:"'Georgia',serif"}}>a house</span></div></div><div style={{height:"1px",background:bdr}}/><div><div style={{fontSize:"11px",color:muted,letterSpacing:"2px",marginBottom:"8px"}}>2025</div><div style={{display:"flex",alignItems:"baseline",gap:"16px"}}><span style={{fontSize:"42px",color:muted,fontFamily:"'Georgia',serif",fontWeight:"bold"}}>$20,000</span><span style={{fontSize:"14px",color:muted}}>=</span><span style={{fontSize:"16px",color:muted,fontFamily:"'Georgia',serif"}}>4 months rent</span></div></div></M><P>The money didn&apos;t change. The money was changed.</P></C> },

  { stage:1, id:"taxes-print", render:()=><C center><div style={{color:sub,fontSize:"14px",fontFamily:"'Georgia',serif",lineHeight:1.6,maxWidth:"300px",textAlign:"left",marginBottom:"16px"}}>&ldquo;Dad, before you go, can I ask you a question?&rdquo;<br/><br/>&ldquo;Sure, son.&rdquo;<br/><br/>&ldquo;Why are we forced to pay taxes? Don&apos;t they print all the money they want anyway?&rdquo;</div><Sp/><div style={{display:"flex",alignItems:"center",gap:"8px"}}><span style={{fontSize:"24px"}}>🕓</span><span style={{color:muted,fontSize:"13px"}}>4:37 AM</span></div><div style={{color:navy,fontSize:"15px",fontFamily:"'Georgia',serif",fontWeight:"bold",marginTop:"12px"}}>It&apos;s theft, son.</div></C> },

  { stage:1, id:"left-vs-right", render:()=><C><T>The argument</T><R2><H2 br><div style={{fontSize:"36px",marginBottom:"8px"}}>🔵</div><div style={{color:"#6495ed",fontSize:"16px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Redistribute</div><div style={{color:sub,fontSize:"12px",marginTop:"4px",textAlign:"center"}}>Take from the top<br/>Give to the bottom</div></H2><H2><div style={{fontSize:"36px",marginBottom:"8px"}}>🔴</div><div style={{color:red,fontSize:"16px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Deregulate</div><div style={{color:sub,fontSize:"12px",marginTop:"4px",textAlign:"center"}}>Get out of the way<br/>Let markets work</div></H2></R2><P>Both assume the ruler is accurate.<br/>What if the ruler is broken?</P></C> },

  { stage:1, id:"dollar-vs-monopoly", render:()=><C center><div style={{display:"flex",gap:"24px",justifyContent:"center",marginBottom:"16px"}}><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>💵</div><div style={{color:sub,fontSize:"12px",marginTop:"4px"}}>US Dollar</div></div><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🎲</div><div style={{color:orange,fontSize:"12px",marginTop:"4px"}}>Monopoly Money</div></div></div><div style={{color:sub,fontSize:"15px",fontFamily:"'Georgia',serif",textAlign:"center",lineHeight:1.6}}>Both are paper.<br/>Both are printed by whoever controls the game.<br/>Neither is backed by anything.</div><P>The only difference is which one<br/>you&apos;ve been told to believe in.</P></C> },

  { stage:1, id:"gold-bar", render:()=><C center><div style={{fontSize:"48px",marginBottom:"8px"}}>🥇</div><div style={{display:"flex",gap:"20px",justifyContent:"center"}}><div style={{textAlign:"center"}}><div style={{color:gold,fontSize:"13px"}}>1920</div><div style={{color:gold,fontSize:"18px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>10 gold bars</div><div style={{color:sub,fontSize:"11px"}}>= a house</div></div><div style={{textAlign:"center"}}><div style={{color:gold,fontSize:"13px"}}>2025</div><div style={{color:gold,fontSize:"18px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>10 gold bars</div><div style={{color:sub,fontSize:"11px"}}>= a house</div></div></div><Sp/><div style={{color:muted,fontSize:"14px",fontFamily:"'Georgia',serif"}}>Gold didn&apos;t go up. The dollar went down.</div><P>The measuring stick shrank.<br/>Not the thing being measured.</P></C> },

  // ───────────────────────────────────────
  // STAGE 2: WHY BITCOIN CAN'T FIX IT (8)
  // ───────────────────────────────────────

  { stage:2, id:"90pct-scams", render:()=><C center><div style={{fontSize:"80px",color:orange,fontFamily:"'Georgia',serif",fontWeight:"bold",lineHeight:1}}>90%</div><div style={{fontSize:"16px",color:sub,marginTop:"8px",fontFamily:"'Georgia',serif"}}>of crypto is scams</div><Sp/><div style={{fontSize:"16px",color:navy,fontFamily:"'Georgia',serif"}}>The other 10% is the most important<br/>technology since the internet.</div><P>The hard part is telling which is which.</P></C> },
  { stage:2, id:"btc-exits", render:()=><C center><T>The Bitcoin lifecycle</T><div style={{display:"flex",flexDirection:"column",gap:"6px",maxWidth:"300px",width:"100%",marginTop:"12px"}}>{["Buy Bitcoin with dollars","Hope number goes up","Number goes up","Sell Bitcoin for... dollars","Celebrate in... dollars"].map((s,i)=><div key={i} style={{display:"flex",gap:"10px",alignItems:"center",padding:"5px 0",borderBottom:`1px solid ${bdr}`}}><div style={{color:i===4?red:orange,fontSize:"13px",fontWeight:"bold",minWidth:"18px"}}>{i+1}.</div><div style={{color:i===4?red:sub,fontSize:"13px",fontFamily:"'Georgia',serif"}}>{s}</div></div>)}</div><P>The escape hatch leads back<br/>to the burning building.</P></C> },
  { stage:2, id:"pizza-math", render:()=><C center><div style={{fontSize:"48px",marginBottom:"12px"}}>🍕</div><div style={{color:orange,fontSize:"11px",letterSpacing:"2px",textTransform:"uppercase",marginBottom:"16px"}}>May 22, 2010</div><div style={{color:sub,fontSize:"15px",fontFamily:"'Georgia',serif",lineHeight:1.8}}>10,000 BTC → 2 pizzas<br/><span style={{color:muted}}>Today those coins =</span><br/><span style={{color:red,fontSize:"24px",fontWeight:"bold"}}>$1,000,000,000</span></div><P>The lesson everyone learned:<br/>never spend Bitcoin. Ever.</P></C> },
  { stage:2, id:"drake-btc", render:()=><C><T>Bitcoin in practice</T><M gap="20px"><div style={{display:"flex",alignItems:"center",gap:"16px",padding:"16px 20px",background:bg2,borderRadius:"12px",border:`1px solid ${bdr}`}}><div style={{width:"48px",height:"48px",borderRadius:"50%",background:"#fee2e2",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"24px",flexShrink:0}}>🙅</div><div><div style={{color:red,fontSize:"16px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Spending Bitcoin</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>&ldquo;That could be worth $47K someday&rdquo;</div></div></div><div style={{display:"flex",alignItems:"center",gap:"16px",padding:"16px 20px",background:`${orange}10`,borderRadius:"12px",border:`1px solid ${orange}33`}}><div style={{width:"48px",height:"48px",borderRadius:"50%",background:"#fef3c7",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"24px",flexShrink:0}}>😌</div><div><div style={{color:orange,fontSize:"16px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Hoarding Bitcoin forever</div><div style={{color:sub,fontSize:"11px",marginTop:"4px"}}>&ldquo;Checking the price 47 times a day&rdquo;</div></div></div></M><P>A currency nobody spends isn&apos;t a currency.</P></C> },
  { stage:2, id:"wallet-ux", render:()=><C center><T>Crypto onboarding</T><div style={{display:"flex",flexDirection:"column",gap:"4px",maxWidth:"280px",width:"100%",marginTop:"12px"}}>{["Download wallet","Write down 24 seed words","Don't lose the paper","Buy ETH for gas fees","Approve the contract","Pay the gas fee","Transaction failed","Pay another gas fee","Wait 47 minutes","Done! (maybe)"].map((s,i)=><div key={i} style={{display:"flex",gap:"8px",alignItems:"center"}}><span style={{color:i===9?teal:muted,fontSize:"11px",minWidth:"16px"}}>{i+1}.</span><span style={{color:i>=6?red:sub,fontSize:"12px"}}>{s}</span></div>)}</div><P>If your mom can&apos;t use it, it&apos;s not ready.</P></C> },
  { stage:2, id:"grandma-explain", render:()=><C center><div style={{fontSize:"48px",marginBottom:"12px"}}>👵</div><div style={{color:sub,fontSize:"14px",fontFamily:"'Georgia',serif",lineHeight:1.8,maxWidth:"300px",textAlign:"left"}}>&ldquo;So it&apos;s like Pok&eacute;mon cards?&rdquo;<br/><br/>&ldquo;No Grandma, it&apos;s different. Just download this app, run this code, and don&apos;t forget this 24-word recovery phrase.&rdquo;<br/><br/>&ldquo;...&rdquo;<br/><br/>&ldquo;Also never share it, write it on paper, hide the paper, and if you lose it your money is gone forever.&rdquo;</div><P>If explaining it sounds insane,<br/>maybe the system is.</P></C> },

  { stage:2, id:"btc-first-mover", render:()=><C><T>Early vs. late adoption</T><R2><H2 br><div style={{fontSize:"48px",marginBottom:"8px"}}>🪙</div><div style={{color:orange,fontSize:"28px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>2012</div><div style={{color:sub,fontSize:"13px",marginTop:"8px",textAlign:"center",lineHeight:1.6}}>Buy 100 BTC<br/>for <span style={{color:orange,fontWeight:"bold"}}>$1,200</span></div><div style={{color:orange,fontSize:"11px",marginTop:"8px"}}>Sit on a beach</div></H2><H2><div style={{fontSize:"48px",marginBottom:"8px"}}>🧱</div><div style={{color:muted,fontSize:"28px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>2030</div><div style={{color:sub,fontSize:"13px",marginTop:"8px",textAlign:"center",lineHeight:1.6}}>Buy 0.01 BTC<br/>for <span style={{color:red,fontWeight:"bold"}}>$1,200</span></div><div style={{color:red,fontSize:"11px",marginTop:"8px"}}>Hope it goes up more</div></H2></R2><P>Same money in. Wildly different outcome.<br/>That&apos;s not a currency. That&apos;s a lottery ticket.</P></C> },

  { stage:2, id:"stablecoin-trap", render:()=><C center><div style={{fontSize:"48px",marginBottom:"16px"}}>🪤</div><div style={{color:orange,fontSize:"20px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>&ldquo;Stablecoins fix this&rdquo;</div><Sp/><div style={{color:sub,fontSize:"14px",lineHeight:1.7,fontFamily:"'Georgia',serif"}}>Pegged to the dollar.<br/>The dollar inflates.<br/>So the stablecoin inflates.</div><P>Electronic fiat is still fiat.</P></C> },

  // STAGE 3: HOW THE ALIGNMENT ECONOMY WORKS (20)
  // ───────────────────────────────────────

  { stage:3, id:"1440-equal", render:()=><C center><div style={{fontSize:"80px",color:teal,fontFamily:"'Georgia',serif",fontWeight:"bold",lineHeight:1}}>1,440</div><div style={{fontSize:"16px",color:teal,marginTop:"8px",fontFamily:"'Georgia',serif",opacity:0.7}}>points per day. Every person. No exceptions.</div><div style={{marginTop:"28px",display:"flex",flexDirection:"column",gap:"6px",width:"100%",maxWidth:"300px"}}>{[["Jeff Bezos","1,440"],["A teacher in Ohio","1,440"],["Person who joined yesterday","1,440"],["Person who joins next year","1,440"]].map(([n,m])=><div key={n as string} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:`1px solid ${bdr}`}}><span style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif"}}>{n}</span><span style={{color:teal,fontSize:"13px",fontWeight:"bold"}}>{m}</span></div>)}</div><P>No early bird advantage. The founder gets<br/>the same as the last person to join.</P></C> },

  { stage:3, id:"use-or-lose", render:()=><C center><div style={{display:"flex",alignItems:"center",gap:"16px"}}><div style={{fontSize:"44px"}}>🌅</div><div style={{color:teal,fontSize:"24px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>+1,440 points</div></div><div style={{color:muted,fontSize:"14px",margin:"20px 0"}}>↓ spend however you want ↓</div><div style={{display:"flex",alignItems:"center",gap:"16px"}}><div style={{fontSize:"44px"}}>🌙</div><div style={{color:red,fontSize:"24px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Unspent = gone</div></div><Sp/><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",lineHeight:1.6}}>BTC: hoard forever. Dollar: watch it melt.<br/>AE: spend it. Live your life. Get more tomorrow.</div></C> },

  { stage:3, id:"bread-stable", render:()=><C center><div style={{fontSize:"48px",marginBottom:"8px"}}>🍞</div><T>What a loaf costs</T><div style={{display:"flex",gap:"24px",justifyContent:"center",marginTop:"16px"}}><div style={{textAlign:"center"}}><div style={{color:red,fontSize:"11px",textTransform:"uppercase",letterSpacing:"1px"}}>US Dollar</div><div style={{display:"flex",flexDirection:"column",gap:"4px",marginTop:"8px"}}>{[["1970","$0.25"],["2000","$1.50"],["2025","$4.50"]].map(([y,p])=><div key={y as string} style={{display:"flex",justifyContent:"space-between",width:"100px",borderBottom:`1px solid ${bdr}`,paddingBottom:"2px"}}><span style={{color:muted,fontSize:"11px"}}>{y}</span><span style={{color:red,fontSize:"11px"}}>{p}</span></div>)}</div></div><div style={{textAlign:"center"}}><div style={{color:teal,fontSize:"11px",textTransform:"uppercase",letterSpacing:"1px"}}>AE</div><div style={{display:"flex",flexDirection:"column",gap:"4px",marginTop:"8px"}}>{[["Day 1","20 pts"],["Day 1,000","20 pts"],["Day 10,000","~20 pts"]].map(([y,p])=><div key={y as string} style={{display:"flex",justifyContent:"space-between",width:"100px",borderBottom:`1px solid ${teal}22`,paddingBottom:"2px"}}><span style={{color:muted,fontSize:"11px"}}>{y}</span><span style={{color:teal,fontSize:"11px"}}>{p}</span></div>)}</div></div></div><P>Rebasing: your number changes,<br/>your purchasing power doesn&apos;t.</P></C> },

  { stage:3, id:"rebasing-pie", render:()=><C center><T>Why your balance changes but your wealth doesn&apos;t</T><div style={{display:"flex",gap:"24px",justifyContent:"center",marginTop:"20px"}}><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🥧</div><div style={{color:teal,fontSize:"20px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>10%</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>of a small pie</div></div><div style={{color:bdr,fontSize:"24px",alignSelf:"center"}}>=</div><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🥧</div><div style={{color:teal,fontSize:"20px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>10%</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>of a big pie</div></div></div><Sp/><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",textAlign:"center",lineHeight:1.6}}>New people join. The pie grows.<br/>Your slice stays the same percentage.<br/>Inflation solved. Deflation solved.</div></C> },

  { stage:3, id:"proof-of-human-ai", render:()=><C center><div style={{fontSize:"48px",marginBottom:"12px"}}>🤖 vs 🧬</div><div style={{color:sub,fontSize:"14px",fontFamily:"'Georgia',serif",marginBottom:"16px"}}>AI can fake a face, voice, and ID.</div><div style={{color:teal,fontSize:"18px",fontFamily:"'Georgia',serif",fontWeight:"bold",lineHeight:1.6}}>It can&apos;t fake 10 real humans<br/>willing to stake their money<br/>that you exist.</div><P>Proof of human, not proof of work.</P></C> },

  { stage:3, id:"ai-why-now", render:()=><C center><T>Why now</T><div style={{display:"flex",flexDirection:"column",gap:"8px",maxWidth:"300px",marginTop:"12px"}}>{[["2020","AI writes essays"],["2023","AI makes videos"],["2024","AI replaces jobs"],["2025","AI fakes humans"],["202?","AI does everything"]].map(([y,d],i)=><div key={y as string} style={{display:"flex",gap:"12px",padding:"4px 0",borderBottom:`1px solid ${bdr}`}}><span style={{color:teal,fontSize:"12px",fontWeight:"bold",minWidth:"36px"}}>{y}</span><span style={{color:i>=3?red:sub,fontSize:"12px"}}>{d}</span></div>)}</div><Sp/><div style={{color:navy,fontSize:"15px",fontFamily:"'Georgia',serif",fontStyle:"italic"}}>The economy was built for a world<br/>where only humans made things.<br/>That world is ending.</div></C> },

  { stage:3, id:"model-t", render:()=><C center><div style={{display:"flex",gap:"16px",justifyContent:"center",marginBottom:"20px"}}><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🐴</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>Fiat</div><div style={{color:muted,fontSize:"9px"}}>Familiar</div></div><div style={{color:bdr,fontSize:"20px",alignSelf:"center"}}>→</div><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🏎️</div><div style={{color:orange,fontSize:"11px",marginTop:"4px"}}>Bitcoin</div><div style={{color:muted,fontSize:"9px"}}>Enthusiast toy</div></div><div style={{color:bdr,fontSize:"20px",alignSelf:"center"}}>→</div><div style={{textAlign:"center"}}><div style={{fontSize:"48px"}}>🚗</div><div style={{color:teal,fontSize:"11px",marginTop:"4px"}}>AE</div><div style={{color:muted,fontSize:"9px"}}>For everyone</div></div></div><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",textAlign:"center",lineHeight:1.6}}>Bitcoin was the proof of concept.<br/>AE is the Model T.</div><P>Not better because someone mandated it.<br/>Better because anyone can use it.</P></C> },

  { stage:3, id:"invisible-now-visible", render:()=><C><T>Now the economy can see</T><M gap="8px">{[["Raising children","→ 1,440 pts/day"],["Caring for aging parents","→ 1,440 pts/day"],["Volunteer firefighting","→ 1,440 pts/day"],["Community organizing","→ 1,440 pts/day"],["Mentoring at-risk youth","→ 1,440 pts/day"]].map(([work,pts])=><div key={work as string} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:`1px solid ${bdr}`}}><span style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif"}}>{work}</span><span style={{color:teal,fontSize:"12px",fontWeight:"bold"}}>{pts}</span></div>)}</M><P>Old system: $0 for all of this.<br/>AE: everyone gets their 1,440. Period.</P></C> },

  { stage:3, id:"build-to-last", render:()=><C><M gap="24px"><div><div style={{display:"flex",alignItems:"center",gap:"12px",marginBottom:"10px"}}><span style={{fontSize:"32px"}}>🪑</span><span style={{color:muted,fontSize:"15px",fontFamily:"'Georgia',serif"}}>Breaks in 2 years</span></div><Bar pct="10%" c="#ccc"/><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>730 days of supportive points</div></div><div><div style={{display:"flex",alignItems:"center",gap:"12px",marginBottom:"10px"}}><span style={{fontSize:"32px"}}>💺</span><span style={{color:gold,fontSize:"15px",fontFamily:"'Georgia',serif"}}>Lasts 20 years</span></div><Bar pct="100%" c={`linear-gradient(90deg,${gold},#f5d76e)`}/><div style={{color:gold,fontSize:"11px",marginTop:"4px"}}>7,300 days of supportive points</div></div></M><P>Build it to break = earn almost nothing.<br/>Build it to last = earn for decades.</P></C> },

  { stage:3, id:"shoes-earn", render:()=><C center><div style={{fontSize:"48px",marginBottom:"8px"}}>👟</div><div style={{color:gold,fontSize:"18px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Your shoes are earning right now.</div><Sp/><div style={{color:sub,fontSize:"13px",lineHeight:1.7}}>Every minute you wear them,<br/>144 daily Supportive points split<br/>across everything you&apos;re using.</div><P>The manufacturer who built them to last<br/>keeps getting paid. For years.</P></C> },

  { stage:3, id:"parks-taxes", render:()=><C><M gap="16px"><div style={{textAlign:"center",fontSize:"13px",color:sub,fontFamily:"'Georgia',serif"}}>Same city. Same budget. Two parks.</div><div style={{padding:"20px",background:`${teal}08`,borderRadius:"12px",border:`1px solid ${teal}22`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:"18px",color:teal,fontFamily:"'Georgia',serif",fontWeight:"bold"}}>🌳 Well maintained</div><div style={{fontSize:"11px",color:muted,marginTop:"4px"}}>People stay for hours</div></div><div style={{fontSize:"28px",color:teal,fontWeight:"bold",fontFamily:"'Georgia',serif"}}>847<span style={{fontSize:"11px",color:muted}}> pts</span></div></div><div style={{padding:"20px",background:bg2,borderRadius:"12px",border:`1px solid ${bdr}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:"18px",color:muted,fontFamily:"'Georgia',serif",fontWeight:"bold"}}>🏚️ Neglected</div><div style={{fontSize:"11px",color:muted,marginTop:"4px"}}>People walk through</div></div><div style={{fontSize:"28px",color:muted,fontWeight:"bold",fontFamily:"'Georgia',serif"}}>31<span style={{fontSize:"11px",color:muted}}> pts</span></div></div></M><P>Ambient points: spaces earn by being<br/>worth spending time in. Taxes by presence.</P></C> },

  { stage:3, id:"city-scorecard", render:()=><C center><T>Government gets a real-time report card</T><div style={{display:"flex",gap:"16px",justifyContent:"center",marginTop:"16px"}}><Box accent={teal}><div style={{fontSize:"28px",marginBottom:"6px"}}>🏙️</div><div style={{color:teal,fontSize:"13px",fontWeight:"bold"}}>City A</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>People moving in</div><div style={{color:teal,fontSize:"16px",fontWeight:"bold",marginTop:"4px"}}>↑ points</div></Box><Box accent={red}><div style={{fontSize:"28px",marginBottom:"6px"}}>🏚️</div><div style={{color:red,fontSize:"13px",fontWeight:"bold"}}>City B</div><div style={{color:muted,fontSize:"11px",marginTop:"4px"}}>People fleeing</div><div style={{color:red,fontSize:"16px",fontWeight:"bold",marginTop:"4px"}}>↓ points</div></Box></div><P>No waiting for elections.<br/>Governance earns, or doesn&apos;t, daily.</P></C> },

  { stage:3, id:"not-communism", render:()=><C center><div style={{display:"flex",flexDirection:"column",gap:"12px",maxWidth:"300px"}}><div style={{color:red,fontSize:"14px",fontFamily:"'Georgia',serif"}}>&ldquo;Isn&apos;t this just communism?&rdquo;</div><Sp/><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",lineHeight:1.7}}>A doctor who saves lives earns more.<br/>A builder who makes quality earns more.<br/>Wealth differences persist.</div><Sp/><div style={{color:teal,fontSize:"14px",fontFamily:"'Georgia',serif"}}>The difference: everyone starts each day<br/>with a floor, not a ceiling.</div></div></C> },

  { stage:3, id:"vouch-privacy", render:()=><C center><div style={{fontSize:"48px",marginBottom:"8px"}}>🔐</div><div style={{color:teal,fontSize:"18px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>Your identity, your choice.</div><div style={{display:"flex",flexDirection:"column",gap:"6px",maxWidth:"280px",marginTop:"16px"}}>{[["Share biometrics","→ fast to 100%"],["Share government ID","→ moderate path"],["Share nothing","→ 10 friends vouch for you"]].map((s,i)=><div key={i} style={{padding:"6px 0",borderBottom:`1px solid ${bdr}`,color:sub,fontSize:"12px",fontFamily:"'Georgia',serif"}}>{s[0]} <span style={{color:teal}}>{s[1]}</span></div>)}</div><P>No identity data on-chain.<br/>Infinite paths to full participation.</P></C> },

  { stage:3, id:"three-flows", render:()=><C center><T>Your attention, three ways</T><div style={{display:"flex",flexDirection:"column",gap:"10px",maxWidth:"300px",width:"100%",marginTop:"12px"}}>{[["Active","You decide where it goes","1,440",teal],["Supportive","Flows to things you're using","144",gold],["Ambient","Flows to spaces you're in","14.4","#6495ed"]].map(([n,d,pts,c])=><div key={n as string} style={{padding:"10px 16px",background:`${c as string}0a`,borderRadius:"8px",border:`1px solid ${c as string}33`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:c as string,fontSize:"14px",fontWeight:"bold",fontFamily:"'Georgia',serif"}}>{n}</div><div style={{color:muted,fontSize:"11px"}}>{d}</div></div><div style={{color:c as string,fontSize:"18px",fontWeight:"bold",fontFamily:"'Courier New',monospace"}}>{pts}</div></div>)}</div></C> },

  { stage:3, id:"deepfake-solved", render:()=><C center><T>The deepfake era</T><div style={{display:"flex",gap:"16px",justifyContent:"center",marginTop:"16px"}}><Box accent={red}><div style={{fontSize:"28px",marginBottom:"6px"}}>🤖</div><div style={{color:red,fontSize:"12px",fontWeight:"bold"}}>AI can fake</div><div style={{color:muted,fontSize:"10px",marginTop:"4px"}}>Faces, voices,<br/>IDs, videos,<br/>entire people</div></Box><Box accent={teal}><div style={{fontSize:"28px",marginBottom:"6px"}}>🧬</div><div style={{color:teal,fontSize:"12px",fontWeight:"bold"}}>AE verifies</div><div style={{color:muted,fontSize:"10px",marginTop:"4px"}}>Real humans,<br/>staked vouches,<br/>skin in the game</div></Box></div><P>Every transaction traceable to a verified human.<br/>Lies become expensive.</P></C> },

  { stage:3, id:"spouse-transfer", render:()=><C center><div style={{fontSize:"48px",marginBottom:"12px"}}>💑</div><div style={{color:sub,fontSize:"14px",fontFamily:"'Courier New',monospace",marginBottom:"12px"}}>ONE WORKS. ONE STAYS HOME.</div><div style={{display:"flex",gap:"8px",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",padding:"12px",background:`${teal}08`,borderRadius:"8px",border:`1px solid ${teal}22`}}><div style={{color:teal,fontSize:"16px",fontWeight:"bold"}}>1,440</div><div style={{color:muted,fontSize:"10px"}}>earner&apos;s pts</div></div><div style={{color:teal,fontSize:"20px"}}>→</div><div style={{textAlign:"center",padding:"12px",background:`${teal}08`,borderRadius:"8px",border:`1px solid ${teal}22`}}><div style={{color:teal,fontSize:"16px",fontWeight:"bold"}}>1,440</div><div style={{color:muted,fontSize:"10px"}}>caregiver&apos;s pts</div></div></div><P>Caregiving isn&apos;t charity anymore.<br/>It&apos;s a visible economic contribution.</P></C> },

  { stage:3, id:"adoption-curve", render:()=><C center><T>How it spreads</T><div style={{display:"flex",flexDirection:"column",gap:"6px",maxWidth:"280px",marginTop:"12px"}}>{[["Phase 1","Enthusiasts try it",orange],["Phase 2","Small communities adopt",gold],["Phase 3","Normal people prefer it",teal],["Phase 4","Old system feels broken",muted]].map(([p,d,c])=><div key={p as string} style={{padding:"8px 12px",borderLeft:`3px solid ${c as string}`,background:bg2,borderRadius:"0 6px 6px 0"}}><div style={{color:c as string,fontSize:"12px",fontWeight:"bold"}}>{p}</div><div style={{color:sub,fontSize:"11px"}}>{d}</div></div>)}</div><Sp/><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",textAlign:"center",lineHeight:1.6}}>Not mandated. Adopted.<br/>Like cars replaced horses.</div></C> },

  { stage:3, id:"elevator-pitch", render:()=><C center><div style={{color:sub,fontSize:"13px",fontFamily:"'Georgia',serif",lineHeight:1.8,maxWidth:"300px",textAlign:"center"}}>The dollar buys less each year.<br/>AI is coming for your job.<br/>Your mom&apos;s contribution isn&apos;t valued.<br/><br/><span style={{color:red}}>The left wants to redistribute.</span><br/><span style={{color:orange}}>The right wants to deregulate.</span><br/><br/><span style={{color:navy}}>Both are missing the point.</span></div><Sp/><div style={{color:teal,fontSize:"17px",fontFamily:"'Georgia',serif",fontWeight:"bold"}}>The measuring stick is broken.</div></C> },

  { stage:3, id:"what-ae-does", render:()=><C center><T>A new way to measure value</T><div style={{display:"flex",flexDirection:"column",gap:"6px",maxWidth:"300px",marginTop:"12px"}}>{["Every human: 1,440 points/day","Things that last earn more","Spaces people love earn more","Bots shrink to nothing","No one can print more","Prices stay stable","Caregiving finally counts"].map(s=><div key={s} style={{color:teal,fontSize:"13px",fontFamily:"'Georgia',serif",padding:"4px 0",borderBottom:`1px solid ${teal}22`}}>✓ {s}</div>)}</div><Sp/><div style={{color:navy,fontSize:"15px",fontFamily:"'Georgia',serif",fontStyle:"italic"}}>alignmenteconomy.org</div></C> },
];

// Export all memes as curated (these are the full replacement set)
export const curatedMemes = memes;
export { memes };
